[package]
name = "video_streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = { version = "0.94.4", features = ["clang-runtime"] }
once_cell = "1.21"
zmq = "0.10.0"
serde_json = "1.0"
chrono = "0.4.41"
